package llms.GUI.Librarian;

import java.util.Locale;
import java.util.ResourceBundle;
import llms.Book.Book;
import llms.Book.BookView;
import llms.Controller;
import static llms.HelperFunctions.tryParseInt;

/**
 * A JFrame to add a book to the database.
 *
 * @author Sevag Saro Aredjian
 */
public class AddBookFrame extends javax.swing.JFrame {

    private boolean isFrench = false;

    /**
     * Creates new form AddBookFrame
     */
    public AddBookFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        publisherLabel = new javax.swing.JLabel();
        publisherInput = new javax.swing.JTextField();
        addedDateLabel = new javax.swing.JLabel();
        addedDateInput = new javax.swing.JTextField();
        serialNumLabel = new javax.swing.JLabel();
        serialNumInput = new javax.swing.JTextField();
        quantityInput = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        issuedInput = new javax.swing.JTextField();
        titleInput = new javax.swing.JTextField();
        issuedLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        addBookButton = new javax.swing.JButton();
        addBookLabel = new javax.swing.JLabel();
        authorInput = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        goBackLabel = new javax.swing.JLabel();
        languageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        publisherLabel.setText("Publisher");

        publisherInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 39, 39)));

        addedDateLabel.setText("Date Added");

        serialNumLabel.setText("Serial Number");

        serialNumInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 39, 39)));

        quantityLabel.setText("Quantity");

        titleInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 39, 39)));

        issuedLabel.setText("Number of Issued Copies");

        titleLabel.setText("Title");

        addBookButton.setText("Add Book");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        addBookLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        addBookLabel.setText("Add a Book");

        authorInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 39, 39)));

        authorLabel.setText("Author");

        goBackLabel.setText("Go to library main page");
        goBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackLabelMouseClicked(evt);
            }
        });

        languageLabel.setText("FR");
        languageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                languageLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goBackLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(publisherLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(publisherInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(authorLabel)
                                            .addComponent(authorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(titleLabel)
                                            .addComponent(titleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(serialNumLabel)
                                            .addComponent(serialNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addedDateLabel)
                                            .addComponent(addedDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(issuedLabel)
                                            .addComponent(issuedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(quantityLabel)
                                            .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(addBookLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(languageLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBookLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serialNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(issuedLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(serialNumInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(issuedInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addedDateLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(authorLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(authorInput)
                    .addComponent(addedDateInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(publisherLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publisherInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBookButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(goBackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseClicked
        new LibrarianFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackLabelMouseClicked

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        if (!serialNumInput.getText().isBlank() && !titleInput.getText().isBlank()
                && !authorInput.getText().isBlank() && !publisherInput.getText().isBlank()
                && ((quantityInput.getText().isBlank() | issuedInput.getText().isBlank())
                | (tryParseInt(issuedInput.getText(), 0) <= tryParseInt(quantityInput.getText(), 1)))) {
            Book book = new Book(serialNumInput.getText(), titleInput.getText(),
                    authorInput.getText(), publisherInput.getText(),
                    tryParseInt(quantityInput.getText(), 1),
                    tryParseInt(issuedInput.getText(), 0), addedDateInput.getText());
            Controller controller = new Controller(book, new BookView(book));
            controller.addBook();
            controller.displayBookDetails();
            dispose();
        }
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void languageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageLabelMouseClicked
        isFrench = !isFrench;
        String lang = "en";
        String country = "CA";
        Locale locale = new Locale(lang, country);
        ResourceBundle res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_en_CA", locale);
        if (isFrench) {
            lang = "fr";
            country = "CA";
            locale = new Locale(lang, country);
            res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_fr_CA", locale);
        }
        languageLabel.setText(res.getString("OTHER_LANG"));
        addBookLabel.setText(res.getString("ADD_BOOK"));
        serialNumLabel.setText(res.getString("SERIAL_NUM"));
        quantityLabel.setText(res.getString("QTE"));
        titleLabel.setText(res.getString("TITLE"));
        issuedLabel.setText(res.getString("ISSUED"));
        authorLabel.setText(res.getString("AUTHOR"));
        addedDateLabel.setText(res.getString("DATE_ADDED"));
        publisherLabel.setText(res.getString("PUBLISHER"));
        addBookButton.setText(res.getString("ADD_BOOK"));
        goBackLabel.setText(res.getString("GO_BACK_LIBRARY"));
    }//GEN-LAST:event_languageLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JLabel addBookLabel;
    private javax.swing.JTextField addedDateInput;
    private javax.swing.JLabel addedDateLabel;
    private javax.swing.JTextField authorInput;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JTextField issuedInput;
    private javax.swing.JLabel issuedLabel;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JTextField publisherInput;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JTextField quantityInput;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField serialNumInput;
    private javax.swing.JLabel serialNumLabel;
    private javax.swing.JTextField titleInput;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
