package llms.GUI.Librarian;

import java.util.Locale;
import java.util.ResourceBundle;
import llms.Book.BookView;
import llms.Controller;
import llms.GUI.HomeFrame;

/**
 * A JFrame allowing librarians to go to add a book, issue a book or to view all
 * issued books.
 *
 * @author Sevag Saro Aredjian
 */
public class LibrarianFrame extends javax.swing.JFrame {

    private boolean isFrench = false;

    /**
     * Creates new form LibrarianFrame
     */
    public LibrarianFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        librarianWelcomeLabel = new javax.swing.JLabel();
        goBackLabel = new javax.swing.JLabel();
        goToAddBookBtn = new javax.swing.JButton();
        goToIssueABookBtn = new javax.swing.JButton();
        goToViewIssuedBtn = new javax.swing.JButton();
        languageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        librarianWelcomeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        librarianWelcomeLabel.setText("Welcome, Librarian");

        goBackLabel.setText("Go to home page");
        goBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackLabelMouseClicked(evt);
            }
        });

        goToAddBookBtn.setText("Add Book");
        goToAddBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAddBookBtnActionPerformed(evt);
            }
        });

        goToIssueABookBtn.setText("Issue a Book");
        goToIssueABookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToIssueABookBtnActionPerformed(evt);
            }
        });

        goToViewIssuedBtn.setText("View Issued Books");
        goToViewIssuedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToViewIssuedBtnActionPerformed(evt);
            }
        });

        languageLabel.setText("FR");
        languageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                languageLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goBackLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(librarianWelcomeLabel)
                            .addComponent(goToViewIssuedBtn)
                            .addComponent(goToAddBookBtn)
                            .addComponent(goToIssueABookBtn))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(librarianWelcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(goToAddBookBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goToIssueABookBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goToViewIssuedBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goBackLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * To allow Librarian to go back to the home page.
     *
     * @param evt The mouse event object.
     */
    private void goBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseClicked
        new HomeFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackLabelMouseClicked

    private void goToAddBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAddBookBtnActionPerformed
        Controller c = new Controller(null, new BookView(null));
        c.displayAddBook();
        dispose();
    }//GEN-LAST:event_goToAddBookBtnActionPerformed

    private void goToIssueABookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToIssueABookBtnActionPerformed
        Controller c = new Controller(null, new BookView(null));
        c.displayIssueBookForm();
        dispose();
    }//GEN-LAST:event_goToIssueABookBtnActionPerformed

    private void goToViewIssuedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToViewIssuedBtnActionPerformed
        Controller c = new Controller(null, new BookView(null));
        c.displayIssueBook();
        dispose();
    }//GEN-LAST:event_goToViewIssuedBtnActionPerformed

    private void languageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageLabelMouseClicked
        isFrench = !isFrench;
        String lang = "en";
        String country = "CA";
        Locale locale = new Locale(lang, country);
        ResourceBundle res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_en_CA", locale);
        if (isFrench) {
            lang = "fr";
            country = "CA";
            locale = new Locale(lang, country);
            res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_fr_CA", locale);
        }
        languageLabel.setText(res.getString("OTHER_LANG"));
        librarianWelcomeLabel.setText(res.getString("LIB_WELCOME"));
        goToAddBookBtn.setText(res.getString("ADD_BOOK"));
        goToIssueABookBtn.setText(res.getString("ISSUE_BOOK"));
        goToViewIssuedBtn.setText(res.getString("VIEW_ISSUED"));
        goBackLabel.setText(res.getString("GO_BACK_HOME"));
    }//GEN-LAST:event_languageLabelMouseClicked

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JButton goToAddBookBtn;
    private javax.swing.JButton goToIssueABookBtn;
    private javax.swing.JButton goToViewIssuedBtn;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JLabel librarianWelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
