package llms.GUI.Student;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import llms.Book.Book;
import llms.Controller;
import llms.Student.Student;
import llms.Student.StudentView;

/**
 * A JFrame allowing students to search for a book.
 *
 * @author Sevag Saro Aredjian
 */
public class BookSearchFrame extends javax.swing.JFrame {

    private Student student;
    private boolean isFrench = false;

    /**
     * Creates new form BookSearchFrame
     */
    public BookSearchFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form BookSearchFrame with a specified Student.
     *
     * @param student The student who is in the current session searching for a
     * book.
     */
    public BookSearchFrame(Student student) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.student = student;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchQueryFieldBtnGroup = new javax.swing.ButtonGroup();
        searchResultScrollPane = new javax.swing.JScrollPane();
        searchResultList = new javax.swing.JList<>();
        goBackLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        searchQueryTextField = new javax.swing.JTextField();
        authorRadioButton = new javax.swing.JRadioButton();
        yearRadioButton = new javax.swing.JRadioButton();
        titleRadioButton = new javax.swing.JRadioButton();
        searchByLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        languageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchResultScrollPane.setViewportView(searchResultList);

        goBackLabel.setText("Go to student main page");
        goBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackLabelMouseClicked(evt);
            }
        });

        searchLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        searchLabel.setText("Search the Library");

        searchQueryFieldBtnGroup.add(authorRadioButton);
        authorRadioButton.setText("Author");

        searchQueryFieldBtnGroup.add(yearRadioButton);
        yearRadioButton.setText("Year");

        searchQueryFieldBtnGroup.add(titleRadioButton);
        titleRadioButton.setText("Title");

        searchByLabel.setText("Search By");

        searchButton.setText("Search Catalog");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        languageLabel.setText("FR");
        languageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                languageLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchByLabel)
                                .addGap(18, 18, 18)
                                .addComponent(authorRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(yearRadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(goBackLabel)
                                .addComponent(searchResultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearRadioButton)
                    .addComponent(titleRadioButton)
                    .addComponent(authorRadioButton)
                    .addComponent(searchByLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goBackLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseClicked
        Controller c = new Controller(student, new StudentView(student));
        c.displayStudentDetails();
        dispose();
    }//GEN-LAST:event_goBackLabelMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchResultList.setModel(new javax.swing.AbstractListModel<String>() {
            List<Book> searchResultsListBook = new ArrayList<>();
            List<String> searchResultsListStr = new ArrayList<>();
            Controller c = new Controller(student, new StudentView(student));

            public void getSearchResults() {
                if (authorRadioButton.isSelected()) {
                    searchResultsListBook = c.searchBookByName(searchQueryTextField.getText());
                } else if (titleRadioButton.isSelected()) {
                    searchResultsListBook = c.searchBookByTitle(searchQueryTextField.getText());
                } else if (yearRadioButton.isSelected()) {
                    searchResultsListBook = c.searchBookByYear(searchQueryTextField.getText());
                } else {
                    searchResultsListBook = Arrays.asList();
                }
            }

            @Override
            public int getSize() {
                getSearchResults();
                return searchResultsListBook.size();
            }

            @Override
            public String getElementAt(int i) {
                searchResultsListBook.forEach((book) -> {
                    searchResultsListStr.add(book.toString());
                });
                return searchResultsListStr.get(i);
            }
        });
    }//GEN-LAST:event_searchButtonActionPerformed

    private void languageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageLabelMouseClicked
        isFrench = !isFrench;
        String lang = "en";
        String country = "CA";
        Locale locale = new Locale(lang, country);
        ResourceBundle res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_en_CA", locale);
        if (isFrench) {
            lang = "fr";
            country = "CA";
            locale = new Locale(lang, country);
            res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_fr_CA", locale);
        }
        languageLabel.setText(res.getString("OTHER_LANG"));
        searchLabel.setText(res.getString("SEARCH_LABEL"));
        searchByLabel.setText(res.getString("SEARCH_BY"));
        authorRadioButton.setText(res.getString("AUTHOR"));
        titleRadioButton.setText(res.getString("TITLE"));
        yearRadioButton.setText(res.getString("YEAR"));
        searchButton.setText(res.getString("SEARCH_BTN"));
        goBackLabel.setText(res.getString("GO_BACK_STUDENT"));
    }//GEN-LAST:event_languageLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton authorRadioButton;
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchByLabel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.ButtonGroup searchQueryFieldBtnGroup;
    private javax.swing.JTextField searchQueryTextField;
    private javax.swing.JList<String> searchResultList;
    private javax.swing.JScrollPane searchResultScrollPane;
    private javax.swing.JRadioButton titleRadioButton;
    private javax.swing.JRadioButton yearRadioButton;
    // End of variables declaration//GEN-END:variables
}
