package llms.GUI.Student;

import java.util.Locale;
import java.util.ResourceBundle;
import llms.Controller;
import llms.GUI.HomeFrame;
import llms.Student.Student;
import llms.Student.StudentView;

/**
 * A JFrame to allow a user to create a new student account.
 *
 * @author Sevag Saro Aredjian
 */
public class StudentRegisterFrame extends javax.swing.JFrame {

    private boolean isFrench = false;

    /**
     * Creates new form StudentRegisterFrame
     */
    public StudentRegisterFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentRegisterLabel = new javax.swing.JLabel();
        studentNameLabel = new javax.swing.JLabel();
        studentNameInput = new javax.swing.JTextField();
        studentIDLabel = new javax.swing.JLabel();
        studentIDInput = new javax.swing.JTextField();
        studentContactNumLabel = new javax.swing.JLabel();
        studentContactNumInput = new javax.swing.JTextField();
        studentRegisterButton = new javax.swing.JButton();
        languageLabel = new javax.swing.JLabel();
        studentLoginLabel = new javax.swing.JLabel();
        goBackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentRegisterLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        studentRegisterLabel.setText("Register");

        studentNameLabel.setText("Name");

        studentNameInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(143, 39, 39)));

        studentIDLabel.setText("Student ID");

        studentContactNumLabel.setText("Contact Number");

        studentRegisterButton.setText("Register");
        studentRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRegisterButtonActionPerformed(evt);
            }
        });

        languageLabel.setText("FR");
        languageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                languageLabelMouseClicked(evt);
            }
        });

        studentLoginLabel.setText("Login");
        studentLoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLoginLabelMouseClicked(evt);
            }
        });

        goBackLabel.setText("Go to home page");
        goBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(studentLoginLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(goBackLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentContactNumLabel)
                            .addComponent(studentNameLabel)
                            .addComponent(studentNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentRegisterLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(studentRegisterButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studentContactNumInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addComponent(studentIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIDLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentRegisterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(studentContactNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentContactNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(studentRegisterButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentLoginLabel)
                    .addComponent(goBackLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentLoginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLoginLabelMouseClicked
        Controller c = new Controller(null, new StudentView(null));
        c.displayStudentLogin();
        dispose();
    }//GEN-LAST:event_studentLoginLabelMouseClicked

    private void studentRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRegisterButtonActionPerformed
        if (!studentIDInput.getText().isBlank() && !studentNameInput.getText().isBlank()
                && !studentContactNumInput.getText().isBlank()) {
            Student student = new Student(studentIDInput.getText(),
                    studentNameInput.getText(), studentContactNumInput.getText());
            Controller c = new Controller(student, new StudentView(student));
            c.addStudent();
            c.displayStudentDetails();
            dispose();
        }
    }//GEN-LAST:event_studentRegisterButtonActionPerformed

    private void goBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseClicked
        new HomeFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackLabelMouseClicked

    private void languageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageLabelMouseClicked
        isFrench = !isFrench;
        String lang = "en";
        String country = "CA";
        Locale locale = new Locale(lang, country);
        ResourceBundle res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_en_CA", locale);
        if (isFrench) {
            lang = "fr";
            country = "CA";
            locale = new Locale(lang, country);
            res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_fr_CA", locale);
        }
        studentRegisterLabel.setText(res.getString("REGISTER"));
        languageLabel.setText(res.getString("OTHER_LANG"));
        studentNameLabel.setText(res.getString("NAME"));
        studentIDLabel.setText(res.getString("ST_ID"));
        studentContactNumLabel.setText(res.getString("CONTACT_NUM"));
        studentLoginLabel.setText(res.getString("LOGIN"));
        studentRegisterButton.setText(res.getString("REGISTER"));
        goBackLabel.setText(res.getString("GO_BACK_HOME"));
    }//GEN-LAST:event_languageLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JTextField studentContactNumInput;
    private javax.swing.JLabel studentContactNumLabel;
    private javax.swing.JTextField studentIDInput;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JLabel studentLoginLabel;
    private javax.swing.JTextField studentNameInput;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JButton studentRegisterButton;
    private javax.swing.JLabel studentRegisterLabel;
    // End of variables declaration//GEN-END:variables
}
