package llms.GUI.Student;

import java.util.Locale;
import java.util.ResourceBundle;
import llms.Controller;
import llms.GUI.HomeFrame;
import llms.Student.Student;
import llms.Student.StudentView;

/**
 * A JFrame allowing students to go to the search or borrow frames.
 *
 * @author Sevag Saro Aredjian
 */
public class StudentFrame extends javax.swing.JFrame {

    private Student student;
    private String notificationMsg;
    private boolean isFrench = false;

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * Creates new form StudentFrame
     *
     * @param student The current student.
     */
    public StudentFrame(Student student) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.student = student;
    }

    /**
     * Creates new form BookSearchFrame with a specified Student.
     *
     * @param student The current student.
     * @param notificationMsg A notification message that will inform the
     * student of his recent action.
     */
    public StudentFrame(Student student, String notificationMsg) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.student = student;
        this.notificationMsg = notificationMsg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageLabel = new javax.swing.JLabel();
        studentWelcomeLabel = new javax.swing.JLabel();
        goToSearchButton = new javax.swing.JButton();
        goToBorrowButton = new javax.swing.JButton();
        studentIdLabel = new javax.swing.JLabel();
        contactNumLabel = new javax.swing.JLabel();
        studentId = new javax.swing.JLabel();
        notificationLabel = new javax.swing.JLabel();
        studentContactNumber = new javax.swing.JLabel();
        notification = new javax.swing.JLabel();
        goBackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        languageLabel.setText("FR");
        languageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                languageLabelMouseClicked(evt);
            }
        });

        studentWelcomeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        studentWelcomeLabel.setText("Welcome,");

        goToSearchButton.setText("Search Book");
        goToSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToSearchButtonActionPerformed(evt);
            }
        });

        goToBorrowButton.setText("Borrow a Book");
        goToBorrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToBorrowButtonActionPerformed(evt);
            }
        });

        studentIdLabel.setText("ID:");

        contactNumLabel.setText("Contact Number:");

        notificationLabel.setText("Notifications:");

        studentContactNumber.setToolTipText("");

        notification.setToolTipText("");

        goBackLabel.setText("Go to home page");
        goBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(languageLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(studentIdLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(studentId))
                                    .addComponent(studentWelcomeLabel)
                                    .addComponent(contactNumLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentContactNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(goToSearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goToBorrowButton))
                            .addComponent(notificationLabel)
                            .addComponent(notification))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goBackLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentWelcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdLabel)
                    .addComponent(studentId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumLabel)
                    .addComponent(studentContactNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goToSearchButton)
                    .addComponent(goToBorrowButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationLabel)
                .addGap(3, 3, 3)
                .addComponent(notification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(goBackLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * To allow Student to go back to the home page.
     *
     * @param evt The mouse event object.
     */
    private void goBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseClicked
        // not called from controller because Home does not belong to StudentView
        // nor BookView
        new HomeFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackLabelMouseClicked

    private void goToSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToSearchButtonActionPerformed
        Controller c = new Controller(student, new StudentView(student));
        c.displaySearchFrame();
        dispose();
    }//GEN-LAST:event_goToSearchButtonActionPerformed

    private void goToBorrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToBorrowButtonActionPerformed
        Controller c = new Controller(student, new StudentView(student));
        c.displayBorrowFrame();
        dispose();
    }//GEN-LAST:event_goToBorrowButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Controller c = new Controller(student, new StudentView(student));
        studentWelcomeLabel.setText("Welcome, " + c.getName());
        studentId.setText(c.getStId() + "");
        studentContactNumber.setText(c.getContactNumber() + "");
        if (notificationMsg != null) {
            notification.setText("You just borrowed "
                    + notificationMsg);
        }
    }//GEN-LAST:event_formWindowOpened

    private void languageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageLabelMouseClicked
        Controller c = new Controller(student, new StudentView(student));
        isFrench = !isFrench;
        String lang = "en";
        String country = "CA";
        Locale locale = new Locale(lang, country);
        ResourceBundle res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_en_CA", locale);
        if (isFrench) {
            lang = "fr";
            country = "CA";
            locale = new Locale(lang, country);
            res = ResourceBundle.getBundle("llms/RessourceBundles/LLMS_fr_CA", locale);
        }
        studentWelcomeLabel.setText(res.getString("WELCOME_STUDENT") + " " + c.getName());
        languageLabel.setText(res.getString("OTHER_LANG"));
        contactNumLabel.setText(res.getString("CONTACT_NUM"));
        goToSearchButton.setText(res.getString("SEARCH_BOOK"));
        goToBorrowButton.setText(res.getString("BORROW_A_BOOK"));
        notificationLabel.setText(res.getString("NOTIFICATIONS"));
        if (notificationMsg != null) {
            notification.setText(res.getString("NOTIFICATION_BORROWED") + " "
                    + notificationMsg);
        }
        goBackLabel.setText(res.getString("GO_BACK_HOME"));
    }//GEN-LAST:event_languageLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactNumLabel;
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JButton goToBorrowButton;
    private javax.swing.JButton goToSearchButton;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JLabel notification;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JLabel studentContactNumber;
    private javax.swing.JLabel studentId;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JLabel studentWelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
